language: go

go:
  - 1.9
  - master

install:
  - go get ./...
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/armon/go-socks5
  - go get github.com/phayes/freeport

matrix:
  allow_failures:
    - go: master
  fast_finish: true

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - ginkgo -r -race
